/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author VSPC-ETERNALSTORM2V5
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuEmpresa = new javax.swing.JMenu();
        itmNuevaEmpresa = new javax.swing.JMenuItem();
        itmEditarEmpresa = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenu();
        itmNuevoEmpleado = new javax.swing.JMenuItem();
        itmEditarEmpleado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuEmpresa.setText("Empresa");

        itmNuevaEmpresa.setText("Nueva Empresa");
        mnuEmpresa.add(itmNuevaEmpresa);

        itmEditarEmpresa.setText("Editar Empresa");
        itmEditarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEditarEmpresaActionPerformed(evt);
            }
        });
        mnuEmpresa.add(itmEditarEmpresa);

        jMenuBar1.add(mnuEmpresa);

        mnuEmpleados.setText("Empleados");

        itmNuevoEmpleado.setText("Nuevo Empleado");
        mnuEmpleados.add(itmNuevoEmpleado);

        itmEditarEmpleado.setText("Editar Empleado");
        mnuEmpleados.add(itmEditarEmpleado);

        jMenuBar1.add(mnuEmpleados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmEditarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEditarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmEditarEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmEditarEmpleado;
    private javax.swing.JMenuItem itmEditarEmpresa;
    private javax.swing.JMenuItem itmNuevaEmpresa;
    private javax.swing.JMenuItem itmNuevoEmpleado;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuEmpleados;
    private javax.swing.JMenu mnuEmpresa;
    // End of variables declaration//GEN-END:variables
}
